# Generated by Django 5.0.6 on 2024-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("exchange", models.CharField(max_length=50)),
                ("assetType", models.CharField(max_length=50)),
                ("ipoDate", models.DateField(null=True)),
            ],
        ),
    ]
