# Generated by Django 5.0.6 on 2024-05-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0003_watchlist_watchlistcompany_watchlist_companies"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="pref_10day",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="pref_30day",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="pref_today",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
