# Generated by Django 5.0.6 on 2024-05-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0004_company_pref_10day_company_pref_30day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="high_10day",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="high_30day",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="high_today",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="low_10day",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="low_30day",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="low_today",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
