# Generated by Django 5.0.6 on 2024-05-14 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0005_company_high_10day_company_high_30day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="pref_10day",
            new_name="perf_10day",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="pref_30day",
            new_name="perf_30day",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="pref_today",
            new_name="perf_today",
        ),
    ]
