# Generated by Django 5.0.6 on 2024-05-14 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0006_rename_pref_10day_company_perf_10day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="ipoDate",
        ),
    ]
